Update Communication.ocl
riseclipse/riseclipse-ocl-constraints-scl2003 pull request #29
Opened 2021-09-03 12:54 UTC by ADehouck

Checks that the MAC-Addresses are unique in the file
issue #28

2021-09-30 13:55 UTC, marcadetd requested changes
I propose to simplify the code, OK ?

2021-10-04 09:24 UTC, ADehouck commented
Yes OK for the simplification
what is the next step, should I Merge the pull request ?

2021-10-04 09:30 UTC, marcadetd commented
Yes, you can merge if you agree

2021-10-04 09:37 UTC, marcadetd approved these changes

2021-10-04 09:38 UTC, merged